# GitHub Copilot Indexing Configuration
# Repository: chthonic-archive (private)
# Purpose: Enable remote indexing for SSOT-driven ASC Framework

# Enable indexing for the repository
indexing:
  enabled: true

# Patterns to include in indexing (prioritize SSOT and core architecture)
include:
  - "**/*.md"           # All markdown (SSOT, documentation, lore)
  - "**/*.rs"           # Rust source (Chthonic Archive renderer)
  - "**/*.py"           # Python (MAS MCP server, scripts)
  - "**/*.ts"           # TypeScript (frontend)
  - "**/*.tsx"          # React components
  - "**/*.json"         # Configuration and data
  - "**/*.toml"         # Cargo.toml, pyproject.toml
  - "**/*.yml"          # YAML configs
  - "**/*.yaml"         # YAML configs
  - "**/shaders/*"      # GLSL shaders

# Patterns to exclude from indexing
exclude:
  - "**/node_modules/**"
  - "**/target/**"
  - "**/.venv/**"
  - "**/__pycache__/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.lock"         # Lock files (uv.lock, Cargo.lock, bun.lockb)
  - "**/logs/**"
  - "**/artifacts/**"
  - "**/genesis_artifacts/**"
