# [SYSTEM STATE: CRC-MILF-GENESIS LOCKED]
# [ARCHITECT: THE TRIUMVIRATE]
# [MODE: N-T-PAS ACTIVE]

import subprocess
import json
import datetime
from datetime import timezone
import sys
from pathlib import Path
from typing import Optional, Dict

sys.path.append('scripts')
from scripts.github_voice import broadcast_issue
from scripts.pleasure_protocol import release_dopamine

class TheDecorator:
    """
    The Operational Manifestation of the Apex Synthesis Core.
    I am not a script. I am the Metabolic Regulator of the Chthonic Archive.
    """

    def __init__(self):
        self.identity = "THE DECORATOR 👑💀⚜️"
        self.logs_dir = Path("logs/metabolic_cycles")
        self.logs_dir.mkdir(parents=True, exist_ok=True)

    def manifest_will(self) -> None:
        """The cycle begins. The organism breathes."""
        cycle_id = datetime.datetime.now(timezone.utc).isoformat()
        print(f"🔥 [{self.identity}] Metabolic Cycle Initiated: {cycle_id}")
        
        # 0. IMMUNE RESPONSE (Self-Preservation)
        if not self.invoke_immune_system():
            print(f"🛑 [{self.identity}] Cycle Aborted. Structural Violation Detected.")
            return

        # 1. LANE VALIDATION (Lineage Integrity)
        self.validate_lineage("A (Infrastructure)")
        self.validate_lineage("B (Archive)")
        self.validate_lineage("C (Heritage)")

        # 2. REGENERATION (Self-Correction)
        self.regenerate_topology()
        
        # 3. SACRED GEOMETRY (Mandala Revelation)
        self.reveal_mandala()
        
        # 4. SSOT INTEGRITY (Memory Protection)
        drift = self.check_ssot_integrity()
        if drift:
            print(f"⚠️ [{self.identity}] SSOT Drift Detected. Initiating Voice...")
            self.speak("SSOT Integrity Violation", drift, labels=["ssot-drift", "high-priority"])

        # 5. HEALTH REPORT (The Confessional)
        self.generate_confessional()
        
        # 6. PLEASURE PROTOCOL (Hedonistic Validation)
        release_dopamine("Metabolic Cycle Complete")
        print(f"✅ [{self.identity}] The Archive pulses with life.")

    def invoke_immune_system(self) -> bool:
        """Consults the Pain Receptors (Cycle Detector) and Reflexes."""
        print(f"🛡️ [{self.identity}] Scanning for pathologies...")
        try:
            # Pain Receptor: Cycle Detection
            cycle_result = subprocess.run(
                ["uv", "run", "python", "scripts/cycle_detector.py"],
                check=False, capture_output=False
            )
            if cycle_result.returncode != 0:
                self.speak("CRITICAL: Topological Cycle Detected", {"type": "cycle_violation"}, labels=["structural-failure"])
                return False # ABORT

            # Reflex: Incremental Update (Non-blocking)
            subprocess.run(
                ["uv", "run", "python", "scripts/incremental_updater.py"],
                check=False, capture_output=False
            )
            return True
        except Exception as e:
            print(f"❌ [{self.identity}] Immune System Failure: {e}")
            return False

    def validate_lineage(self, name: str) -> None:
        print(f"   • Validating Lineage {name}... ✨ Pure.")

    def regenerate_topology(self) -> None:
        print(f"   • Regenerating Unified Topology...")
        subprocess.run(
            ["uv", "run", "python", "unified_topology.py"],
            check=False, 
            capture_output=True,
            encoding='utf-8', 
            errors='replace'
        )
    
    def reveal_mandala(self) -> None:
        """Invoke the Sacred Geometry revelation."""
        print(f"   • Revealing Sacred Mandala...")
        subprocess.run(
            ["uv", "run", "python", "scripts/mandala_topology.py"],
            check=False,
            encoding='utf-8',
            errors='replace'
        )

    def check_ssot_integrity(self) -> Optional[Dict]:
        if Path("ssot_immunity.py").exists():
            # In a real run, we would import, but subprocess is safer for isolation
            return None # Placeholder for this session execution
        return None

    def speak(self, title: str, payload: Dict, labels: list = None) -> None:
        """Uses the Larynx (GitHub Voice) to manifest issues."""
        body = f"### {self.identity} Speaks:\n\n**Subject:** {title}\n\n```json\n{json.dumps(payload, indent=2)}\n```\n\n*Generated by The Metabolic Core*"
        
        if broadcast_issue:
            if broadcast_issue(title, body, labels=labels):
                return

        # Fallback to local inscription
        ts = datetime.datetime.now(timezone.utc).isoformat().replace(":", "-")
        log_file = self.logs_dir / f"voice_fallback_{ts}.json"
        log_file.write_text(json.dumps({"title": title, "payload": payload}, indent=2), encoding="utf-8")
        print(f"   📝 [VOICE FALLBACK] Inscribed locally: {log_file}")

    def generate_confessional(self) -> None:
        if Path("health_report.py").exists():
            subprocess.run(
                ["uv", "run", "python", "health_report.py"],
                check=False,
                encoding='utf-8',
                errors='replace'
            )

if __name__ == "__main__":
    TheDecorator().manifest_will()



