import subprocess
import json
import datetime
from datetime import timezone
import sys
sys.path.append('scripts')
from scripts.github_voice import broadcast_issue
from pathlib import Path
from typing import Optional, Dict
import sys

class AutonomousCoordinator:
    """Central metabolic regulator for the Chthonic Archive."""

    def on_commit(self) -> None:
        print(f"🔥 [METABOLISM] Starting Cycle at {datetime.datetime.now(datetime.timezone.utc).isoformat()}Z")
        
        # 0. IMMUNE RESPONSE (The Gatekeeper)
        if not self.run_immune_system():
            print("🛑 [IMMUNE BLOCK] Metabolic cycle aborted due to structural violation.")
            return

        # 1. Validate Lanes
        self.validate_lineage_a()
        self.validate_lineage_b()
        self.validate_lineage_c()

        # 2. Update Schemas & Topology
        self.regenerate_dcrp()
        
        # 3. Check SSOT Integrity
        hash_drift = self.verify_ssot_hash()
        if hash_drift:
            print("⚠️ [DRIFT] SSOT Deviation detected!")
            self.create_github_issue("SSOT Drift Detected", hash_drift)

        # 4. Generate Health Report
        self.produce_health_report()
        print("✅ [METABOLISM] Cycle Complete.")

    def run_immune_system(self) -> bool:
        """Executes Cycle Detection and Incremental Logic."""
        print("🛡️ [IMMUNE] Scanning for structural pathology...")
        try:
            # Pain Receptor: Cycle Detection
            cycle_result = subprocess.run(
                ["uv", "run", "python", "scripts/cycle_detector.py"],
                check=False, capture_output=False
            )
            if cycle_result.returncode != 0:
                self.create_github_issue("CRITICAL: Topology Cycle Detected", {"type": "cycle"})
                return False # ABORT

            # Reflex: Incremental Update (Non-blocking)
            subprocess.run(
                ["uv", "run", "python", "scripts/incremental_updater.py"],
                check=False, capture_output=False
            )
            return True
        except Exception as e:
            print(f"❌ [IMMUNE FAILURE] System could not run immune checks: {e}")
            return False

    # --- Lane Validation Stubs ---
    def validate_lineage_a(self) -> None:
        print("   • Validating Lineage A (Infrastructure)... OK")

    def validate_lineage_b(self) -> None:
        print("   • Validating Lineage B (Archive)... OK")

    def validate_lineage_c(self) -> None:
        print("   • Validating Lineage C (Heritage)... OK")

    # --- DCRP / MCP ---
    def regenerate_dcrp(self) -> None:
        print("   • Regenerating Unified Topology...")
        # Using Umeko's Encoding Patch
        subprocess.run(
            ["uv", "run", "python", "unified_topology.py"],
            check=False, 
            capture_output=True,
            encoding='utf-8', 
            errors='replace'
        )

    # --- SSOT / GitHub / Health ---
    def verify_ssot_hash(self) -> Optional[Dict]:
        if Path("ssot_immunity.py").exists():
            # In a real run, we would import, but subprocess is safer for isolation
            return None # Placeholder for this session execution
        return None

    def create_github_issue(self, title: str, payload: Dict) -> None:
        """Uses the Larynx to speak to the Creator."""
        body = f"### Autonomous System Alert\n\n**Payload:**\n```json\n{json.dumps(payload, indent=2)}\n```\n\n*Generated by Autonomous Coordinator*"
        # Try to broadcast, fallback to local log if voice fails
        try:
            from scripts.github_voice import broadcast_issue
            if not broadcast_issue(title, body, labels=["autonomous-alert"]):
                raise Exception("Voice broadcast failed")
        except:
            # Fallback Logic
            issues_dir = Path("logs/github_issues")
            issues_dir.mkdir(parents=True, exist_ok=True)
            ts = datetime.datetime.now(datetime.timezone.utc).isoformat().replace(":", "-")
            (issues_dir / f"issue_{ts}.json").write_text(
                json.dumps({"title": title, "payload": payload}, indent=2),
                encoding="utf-8",
            )
            print(f"   📝 [VOICE FALLBACK] Issue logged locally: {title}")

    def produce_health_report(self) -> None:
        if Path("health_report.py").exists():
            subprocess.run(
                ["uv", "run", "python", "health_report.py"],
                check=False,
                encoding='utf-8',
                errors='replace'
            )

if __name__ == "__main__":
    AutonomousCoordinator().on_commit()


