# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "json", "~> 2.5"

gem "tk", "~> 0.6" # Ruby 4.0-compatible Tk line

gem "sqlite3", "~> 2.9" # Ruby 4.0-compatible sqlite3 series
