import type { MdsealProviderRegistryEntry } from "./types";

export const providerRegistry: MdsealProviderRegistryEntry[] = [
  { id: "null-provider", displayName: "Null Provider", kind: "formula-ocr", modelId: null, adapter: "null", status: "disabled", offlineSupport: "yes", expectedRuntime: "unknown", windowsSupport: "yes", licenseNote: "built-in", installHint: "none", knownWeaknesses: ["returns no result"], outputContract: "null", requiresNetworkForInstall: false, mayTriggerModelDownload: false },
  { id: "pix2text-mfr", displayName: "Pix2Text MFR", kind: "formula-ocr", modelId: "pix2text-mfr", adapter: "python-stdio", status: "planned", offlineSupport: "yes", expectedRuntime: "cpu", windowsSupport: "partial", licenseNote: "varies", installHint: "pip install pix2text", knownWeaknesses: ["math-heavy images", "layout drift"], outputContract: "latex/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "pix2tex-compatible", displayName: "Pix2Tex Compatible", kind: "formula-ocr", modelId: "pix2tex-compatible", adapter: "python-stdio", status: "planned", offlineSupport: "partial", expectedRuntime: "gpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "pip install pix2tex", knownWeaknesses: ["needs clean crops"], outputContract: "latex/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "paddleocr-vl-formula", displayName: "PaddleOCR-VL Formula", kind: "formula-ocr", modelId: "paddleocr-vl-formula", adapter: "python-stdio", status: "planned", offlineSupport: "partial", expectedRuntime: "cpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "pip install paddleocr", knownWeaknesses: ["formula specialization"], outputContract: "latex/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "chandra-ocr-2", displayName: "Chandra OCR 2", kind: "document-ocr", modelId: "chandra-ocr-2", adapter: "python-stdio", status: "planned", offlineSupport: "partial", expectedRuntime: "gpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "see model card", knownWeaknesses: ["document layout"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "paddleocr-vl-document", displayName: "PaddleOCR-VL Document", kind: "document-ocr", modelId: "paddleocr-vl-document", adapter: "python-stdio", status: "planned", offlineSupport: "partial", expectedRuntime: "cpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "pip install paddleocr", knownWeaknesses: ["tables", "math"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "qianfan-ocr", displayName: "Qianfan OCR", kind: "document-ocr", modelId: "qianfan-ocr", adapter: "external-command", status: "planned", offlineSupport: "no", expectedRuntime: "unknown", windowsSupport: "unknown", licenseNote: "service-backed", installHint: "configure external command", knownWeaknesses: ["network dependence"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: false },
  { id: "numarkdown-8b-thinking", displayName: "Numarkdown 8B Thinking", kind: "document-ocr", modelId: "numarkdown-8b-thinking", adapter: "python-stdio", status: "planned", offlineSupport: "partial", expectedRuntime: "gpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "see model card", knownWeaknesses: ["slow", "heavy"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "nanonets-ocr2", displayName: "Nanonets OCR2", kind: "document-ocr", modelId: "nanonets-ocr2", adapter: "external-command", status: "planned", offlineSupport: "no", expectedRuntime: "unknown", windowsSupport: "unknown", licenseNote: "service-backed", installHint: "configure external service", knownWeaknesses: ["network dependence"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: false },
  { id: "olmocr-compatible", displayName: "OLM OCR Compatible", kind: "document-ocr", modelId: "olmocr-compatible", adapter: "python-stdio", status: "planned", offlineSupport: "yes", expectedRuntime: "cpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "see model card", knownWeaknesses: ["layout fidelity"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "granite-docling", displayName: "Granite Docling", kind: "document-ocr", modelId: "granite-docling", adapter: "python-stdio", status: "planned", offlineSupport: "partial", expectedRuntime: "gpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "see model card", knownWeaknesses: ["table fidelity"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "surya-ocr", displayName: "Surya OCR", kind: "document-ocr", modelId: "surya-ocr", adapter: "python-stdio", status: "planned", offlineSupport: "partial", expectedRuntime: "gpu", windowsSupport: "partial", licenseNote: "check upstream", installHint: "pip install surya-ocr", knownWeaknesses: ["GPU preferred"], outputContract: "markdown/confidence/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "sentence-transformers-compatible", displayName: "Sentence Transformers Compatible", kind: "embedding", modelId: "sentence-transformers-compatible", adapter: "python-stdio", status: "planned", offlineSupport: "yes", expectedRuntime: "cpu", windowsSupport: "yes", licenseNote: "model-dependent", installHint: "pip install sentence-transformers", knownWeaknesses: ["model choice varies"], outputContract: "vector/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "transformers-js-embedding", displayName: "Transformers JS Embedding", kind: "embedding", modelId: "transformers-js-embedding", adapter: "transformers-js", status: "planned", offlineSupport: "partial", expectedRuntime: "webgpu", windowsSupport: "partial", licenseNote: "browser/runtime dependent", installHint: "npm install @xenova/transformers", knownWeaknesses: ["WebGPU availability"], outputContract: "vector/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
  { id: "local-bge-compatible", displayName: "Local BGE Compatible", kind: "embedding", modelId: "local-bge-compatible", adapter: "python-stdio", status: "planned", offlineSupport: "yes", expectedRuntime: "cpu", windowsSupport: "yes", licenseNote: "model-dependent", installHint: "see local BGE docs", knownWeaknesses: ["embedding drift"], outputContract: "vector/model", requiresNetworkForInstall: true, mayTriggerModelDownload: true },
];

export const providerById = new Map(providerRegistry.map((entry) => [entry.id, entry]));
