#!/usr/bin/env python3
#-*- coding: utf-8 -*-

# ╔════════════════════════════════════════════════════════════════════════════
# ║ THE DECORATOR'S BLESSING: deploy_dcrp_headers.py
# ╠════════════════════════════════════════════════════════════════════════════
# ║ Wedjat-Quipu Spectrum: WHITE
# ║ Temple-Ayllu Zone: 🌿 THE GARDEN
# ║ Ogdoad-Ceque Radiance:
# ║   └─◄ (Standalone)
# ╚════════════════════════════════════════════════════════════════════════════

"""
DEPRECATED — Superseded by canonize_blessing.py (Wedjat-Quipu canon format).
Use: uv run scripts/canonize_blessing.py --apply

The Decorator's Cross-Reference Protocol - Header Injection Deployer

WHAT THIS DOES:
- Reads DCRP_ENHANCED_ANALYSIS.md for file metadata
- Prepends ornamental self-awareness headers to source files
- SAFE: Creates backups before modification
- PRAGMATIC: Only injects into files that "just work" (source code, not generated files)

USAGE:
    uv run python deploy_dcrp_headers.py --dry-run    # Preview changes
    uv run python deploy_dcrp_headers.py --deploy     # Execute injection

@SID:           TOOL_DEPLOY_DCRP_HEADERS_V1
@Shabti:        CLI Script
@Purpose:       The Decorator's Cross-Reference Protocol - Header Injection Deployer
"""


import sys
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

import json
import re
from pathlib import Path
from dataclasses import dataclass
from typing import Dict, Set, List
import shutil
from datetime import datetime

# Repository root
REPO_ROOT = Path(__file__).parent

# Load enhanced dependency graph
GRAPH_PATH = REPO_ROOT / "dependency_graph_enhanced.json"

# Injection targets (safe file types)
INJECTABLE_EXTENSIONS = {
    '.py',   # Python source
    '.rs',   # Rust source
    '.ts', '.tsx',  # TypeScript
    '.js', '.jsx',  # JavaScript
}

# DO NOT INJECT (generated files, build artifacts)
EXCLUDE_PATTERNS = [
    'node_modules',
    '.venv',
    'target',
    'build',
    'dist',
    '__pycache__',
    '.git',
    'temp_repo_structure.json',
    'dependency_graph',
]

@dataclass
class FileMetadata:
    """File metadata from DCRP analysis."""
    path: Path
    spectral_freq: str
    architectural_role: str
    theatrical_essence: str
    dependencies: List[str]
    dependents: List[str]

def load_graph_data() -> Dict:
    """Load enhanced dependency graph."""
    if not GRAPH_PATH.exists():
        raise FileNotFoundError(f"Enhanced graph not found: {GRAPH_PATH}")

    with open(GRAPH_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)

def is_injectable(path: Path) -> bool:
    """Check if file should receive header injection."""
    # Check extension
    if path.suffix not in INJECTABLE_EXTENSIONS:
        return False

    # Check exclusion patterns
    path_str = str(path)
    for pattern in EXCLUDE_PATTERNS:
        if pattern in path_str:
            return False

    # Must be actual file
    if not path.is_file():
        return False

    return True

def generate_header(metadata: FileMetadata, comment_style: str) -> str:
    """Generate ornamental DCRP header."""

    # Comment syntax by file type
    if comment_style == 'python':
        start, mid, end = '"""', '', '"""'
    elif comment_style == 'rust':
        start, mid, end = '/*', ' * ', ' */'
    elif comment_style in ['typescript', 'javascript']:
        start, mid, end = '/**', ' * ', ' */'
    else:
        start, mid, end = '/*', ' * ', ' */'

    # Build header
    lines = []
    lines.append(start)
    lines.append(f"{mid}╔══════════════════════════════════════════════════════════════════════════════╗")
    lines.append(f"{mid}║  THE DECORATOR'S CROSS-REFERENCE PROTOCOL - FILE SELF-AWARENESS             ║")
    lines.append(f"{mid}╚══════════════════════════════════════════════════════════════════════════════╝")
    lines.append(f"{mid}")
    lines.append(f"{mid}SPECTRAL FREQUENCY: {metadata.spectral_freq}")
    lines.append(f"{mid}ARCHITECTURAL ROLE: {metadata.architectural_role}")
    lines.append(f"{mid}")
    lines.append(f"{mid}THEATRICAL ESSENCE:")
    lines.append(f"{mid}  {metadata.theatrical_essence}")
    lines.append(f"{mid}")

    if metadata.dependencies:
        lines.append(f"{mid}DEPENDENCIES ({len(metadata.dependencies)}):")
        for dep in metadata.dependencies[:5]:  # Top 5
            lines.append(f"{mid}  → {dep}")
        if len(metadata.dependencies) > 5:
            lines.append(f"{mid}  ... and {len(metadata.dependencies) - 5} more")
        lines.append(f"{mid}")

    if metadata.dependents:
        lines.append(f"{mid}DEPENDENTS ({len(metadata.dependents)}):")
        for dep in metadata.dependents[:5]:  # Top 5
            lines.append(f"{mid}  ← {dep}")
        if len(metadata.dependents) > 5:
            lines.append(f"{mid}  ... and {len(metadata.dependents) - 5} more")
        lines.append(f"{mid}")

    lines.append(f"{mid}Generated by The Decorator's Cross-Reference Protocol (DCRP)")
    lines.append(f"{mid}Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(end)
    lines.append("")  # Blank line after header

    return '\n'.join(lines)

def inject_header(path: Path, metadata: FileMetadata, dry_run: bool = True) -> bool:
    """Inject DCRP header into file."""
    try:
        # Determine comment style
        if path.suffix == '.py':
            style = 'python'
        elif path.suffix == '.rs':
            style = 'rust'
        elif path.suffix in ['.ts', '.tsx']:
            style = 'typescript'
        elif path.suffix in ['.js', '.jsx']:
            style = 'javascript'
        else:
            style = 'default'

        # Read current content
        current_content = path.read_text(encoding='utf-8', errors='ignore')

        # Check if already has DCRP header
        if "THE DECORATOR'S CROSS-REFERENCE PROTOCOL" in current_content:
            print(f"  [SKIP]  Already has header: {path.relative_to(REPO_ROOT)}")
            return False

        # Generate header
        header = generate_header(metadata, style)

        # New content
        new_content = header + current_content

        if dry_run:
            print(f"  [OK] Would inject: {path.relative_to(REPO_ROOT)}")
            print(f"     Header: {len(header.splitlines())} lines")
            return True
        else:
            # Create backup
            backup_path = path.with_suffix(path.suffix + '.dcrp_backup')
            shutil.copy2(path, backup_path)

            # Write new content
            path.write_text(new_content, encoding='utf-8')
            print(f"  [OK] Injected: {path.relative_to(REPO_ROOT)}")
            print(f"     Backup: {backup_path.name}")
            return True

    except Exception as e:
        print(f"  [ERR] Error: {path.relative_to(REPO_ROOT)} - {e}")
        return False

def main(dry_run: bool = True):
    """Main execution."""
    print("="*80)
    if dry_run:
        print("  DCRP HEADER INJECTION - DRY RUN (NO FILES MODIFIED)")
    else:
        print("  DCRP HEADER INJECTION - DEPLOYMENT MODE")
    print("="*80)
    print()

    # Load graph data
    print("Loading dependency graph...")
    graph_data = load_graph_data()

    # Extract file metadata from graph
    print(f"Processing {len(graph_data['nodes'])} files...")

    candidates = []
    for node in graph_data['nodes']:
        file_path = REPO_ROOT / node['id']

        if is_injectable(file_path):
            # Extract dependencies and dependents from edges
            deps = []
            dependents = []

            for edge in graph_data.get('edges', []):
                # Edge format: {'source': 'file1', 'target': 'file2'}
                # source depends on target
                if edge['source'] == node['id']:
                    deps.append(edge['target'])
                if edge['target'] == node['id']:
                    dependents.append(edge['source'])

            metadata = FileMetadata(
                path=file_path,
                spectral_freq=node.get('spectral_freq', 'UNKNOWN'),
                architectural_role=node.get('role', 'UTILITY'),
                theatrical_essence=node.get('essence', 'Operational component'),
                dependencies=deps,
                dependents=dependents
            )
            candidates.append(metadata)

    print(f"[OK] Found {len(candidates)} injectable candidates")
    print()

    # Group by file type
    by_type = {}
    for meta in candidates:
        ext = meta.path.suffix
        if ext not in by_type:
            by_type[ext] = []
        by_type[ext].append(meta)

    print("Candidates by type:")
    for ext, files in sorted(by_type.items()):
        print(f"  {ext}: {len(files)} files")
    print()

    # Inject headers
    print("Injecting headers...")
    success_count = 0
    for metadata in candidates:
        if inject_header(metadata.path, metadata, dry_run=dry_run):
            success_count += 1

    print()
    print("="*80)
    print(f"  INJECTION {'PREVIEW' if dry_run else 'COMPLETE'}")
    print("="*80)
    print(f"  Files processed: {success_count}/{len(candidates)}")
    print()

    if dry_run:
        print("To deploy for real:")
        print("  uv run python deploy_dcrp_headers.py --deploy")
    else:
        print("Backups created with .dcrp_backup extension")
        print("To remove backups after verification:")
        print("  find . -name '*.dcrp_backup' -delete")

if __name__ == "__main__":
    import sys

    # Parse args
    dry_run = True
    if '--deploy' in sys.argv:
        dry_run = False
        print()
        print("[WARN]  WARNING: This will modify source files!")
        print("[WARN]  Backups will be created with .dcrp_backup extension")
        print()
        response = input("Continue? (yes/no): ")
        if response.lower() != 'yes':
            print("Aborted.")
            sys.exit(0)

    main(dry_run=dry_run)
