#!/usr/bin/env python3
#-*- coding: utf-8 -*-

# ╔════════════════════════════════════════════════════════════════════════════
# ║ THE DECORATOR'S BLESSING: map_codebase.py
# ╠════════════════════════════════════════════════════════════════════════════
# ║ Wedjat-Quipu Spectrum: WHITE
# ║ Temple-Ayllu Zone: 🌿 THE GARDEN
# ║ Ogdoad-Ceque Radiance:
# ║   └─◄ (Standalone)
# ╚════════════════════════════════════════════════════════════════════════════

"""
map_codebase.py — Codebase Cartographer & README Proposer

@SID:           TOOL_CODEBASE_MAPPER_V1
@Shabti:          Script
@Context:       Documentation / Inventory
@Implements:    CONCEPT_CODEBASE_CARTOGRAPHY
@Emits:         STATE_CODEBASE_INVENTORY
@Related:       TOOL_ROOT_AUDIT_V1
@Purpose:       map_codebase.py — Codebase Cartographer & README Proposer

Traverses the repository to:
1. Map the directory structure.
2. Inventory files by type.
3. Check for existing README.md files.
4. Propose a standardized README implementation for unmapped territories.

Usage:
    uv run scripts/map_codebase.py
"""

from __future__ import annotations


import sys
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

import os
from collections import defaultdict
from pathlib import Path
from typing import NamedTuple

import argparse
import sys

# sys.path guard: ensure repo root is importable regardless of invocation CWD
_REPO_ROOT_CANDIDATE = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT_CANDIDATE) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT_CANDIDATE))

from scripts.lib.shared import find_repo_root as _find_repo_root

# Configuration
IGNORE_DIRS = {
    ".git", "node_modules", ".venv", "__pycache__", "dist", ".bun",
    "target", ".vscode", "extensions", "build"
}
# Actually, let's look inside extensions but ignore their build artifacts
DEEP_IGNORE = {"node_modules", "target", "__pycache__", "build"}

class FolderStats(NamedTuple):
    file_counts: dict[str, int]
    has_readme: bool
    readme_path: Path | None
    total_size: int

def scan_tree(root: Path) -> dict[Path, FolderStats]:
    """Recursively map the codebase."""
    mapping = {}

    try:
        for dirpath, dirnames, filenames in os.walk(root):
            # In-place filtering of directories
            dirnames[:] = [d for d in dirnames if d not in DEEP_IGNORE and not d.startswith(".")]

            current_path = Path(dirpath)

            # Skip top-level ignored dirs completely
            if current_path != root and (current_path.name in IGNORE_DIRS or current_path.parts[0] in IGNORE_DIRS):
                continue

            stats = defaultdict(int)
            total_size = 0
            has_readme = False
            readme_path = None

            for f in filenames:
                ext = Path(f).suffix.lower() or "(no-ext)"
                stats[ext] += 1
                try:
                    total_size += (current_path / f).stat().st_size
                except OSError:
                    pass # Resilience: Skip unreadable files

                if f.lower() == "readme.md":
                    has_readme = True
                    readme_path = current_path / f

            rel_path = current_path.relative_to(root)

            mapping[rel_path] = FolderStats(
                file_counts=dict(stats),
                has_readme=has_readme,
                readme_path=readme_path,
                total_size=total_size
            )
    except Exception as e:
        print(f"Error during scan: {e}", file=sys.stderr)

    return mapping

def generate_proposal(mapping: dict[Path, FolderStats]) -> str:
    lines = [
        "# Codebase Inventory & README Proposal",
        "",
        "> **Generated by:** `TOOL_CODEBASE_MAPPER_V1`",
        "> **Status:** `STABLE_STATE` (Updates overwrite)",
        "",
        "<!--",
        "================================================================================",
        "SEMANTIC IDENTITY (Anchor & Signal Protocol)",
        "================================================================================",
        "@SID:           STATE_CODEBASE_INVENTORY",
        "@Type:          State",
        "@Context:       Inventory",
        "@UpdateFrequency: On-Demand",
        "@SessionOrigin: SESSION_DOC_2026_01_17_CLEANUP",
        "================================================================================",
        "-->",
        "",
        "## Strategic Inventory",
        "",
        "| Directory | Status | Primary Content | Action Required |",
        "|-----------|--------|-----------------|-----------------|"
    ]

    sorted_paths = sorted(mapping.keys(), key=lambda p: (len(p.parts), p.name))

    for path in sorted_paths:
        if str(path) == ".":
            path_str = "/"
        else:
            path_str = str(path).replace("\\", "/")

        stats = mapping[path]

        if stats.has_readme:
            status = "✅ Documented"
            action = "Maintain"
        else:
            status = "⚠️ Uncharted"
            action = "Create README"

        if not stats.file_counts:
            content = "(Empty/Dirs only)"
        else:
            top_ext = max(stats.file_counts.items(), key=lambda x: x[1])[0]
            content = f"{top_ext} ({stats.file_counts[top_ext]})"

        lines.append(f"| `{path_str}` | {status} | {content} | {action} |")

    lines.extend([
        "",
        "## Implementation Proposal",
        "",
        "### Standardized README Structure",
        "",
        "Every directory identified as **Uncharted** above requires a `README.md` implementing the **Folder Identity Protocol**:",
        "",
        "```markdown",
        "# Directory: [Name]",
        "",
        "## Purpose",
        "[Brief description of why this folder exists and what it contains]",
        "",
        "## Contents",
        "- `*.ext`: [Description of file types]",
        "- `subfolder/`: [Description of sub-components]",
        "",
        "## Ownership",
        "- **Steward:** [Role/Script Name]",
        "- **Update Frequency:** [Static/Dynamic/Archived]",
        "```",
        "",
        "### Strategic Priority",
        "",
        "1. **Core Infrastructure** (`scripts/`, `src/`) - High Priority",
        "2. **Documentation** (`docs/`) - Medium Priority (Self-documenting, but needs structure)",
        "3. **Archives** (`dumpster-dive/`) - Low Priority (Static)",
        ""
    ])

    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="Codebase Cartographer & README Proposer")
    parser.add_argument("--dry-run", action="store_true", help="Print output to stdout instead of writing file")
    parser.add_argument(
        "--output", "-o", type=Path, default=None,
        help="Explicit output file path (overrides SID anchor resolution).",
    )
    args = parser.parse_args()

    root = _find_repo_root()
    print(f"Mapping codebase from: {root}")

    mapping = scan_tree(root)
    report = generate_proposal(mapping)

    # Dynamic Output Path Resolution (Anchor & Signal Protocol)
    if args.output:
        output_path = args.output
        print(f"Using explicit output path: {output_path}")
    else:
        target_sid = "STATE_CODEBASE_INVENTORY"
        default_path = root / "docs" / "CODEBASE_INVENTORY.md"

        found_path = None
        docs_dir = root / "docs"
        if docs_dir.exists():
            try:
                for md_file in docs_dir.glob("*.md"):
                    try:
                        content = md_file.read_text(encoding="utf-8", errors="ignore")
                        if f"@SID:           {target_sid}" in content or f"@SID: {target_sid}" in content:
                            found_path = md_file
                            break
                    except OSError:
                        continue
            except OSError:
                pass

        if found_path:
            output_path = found_path
            print(f"Resolving output to existing State File: {output_path}")
        else:
            output_path = default_path
            print(f"State File not found. Creating default: {output_path}")

    if args.dry_run:
        print("\n[DRY RUN] Output content preview:")
        print("-" * 40)
        print(report)
        print("-" * 40)
        print(f"[DRY RUN] Would write to: {output_path}")
    else:
        try:
            output_path.parent.mkdir(exist_ok=True)
            output_path.write_text(report, encoding="utf-8")
            print(f"Map generated: {output_path}")
        except OSError as e:
            print(f"Error writing output: {e}", file=sys.stderr)

    print(f"Total directories scanned: {len(mapping)}")

if __name__ == "__main__":
    main()
