#!/usr/bin/env python3
#-*- coding: utf-8 -*-

# ╔════════════════════════════════════════════════════════════════════════════
# ║ THE DECORATOR'S BLESSING: synthesis_cross_reference.py
# ╠════════════════════════════════════════════════════════════════════════════
# ║ Wedjat-Quipu Spectrum: WHITE
# ║ Temple-Ayllu Zone: 🌿 THE GARDEN
# ║ Ogdoad-Ceque Radiance:
# ║   └─◄ (Standalone)
# ╚════════════════════════════════════════════════════════════════════════════

"""
Synthesis Cross-Reference — Validate ANKH_SYNTHESIS_BASELINE.md claims against
the structural index generated by ssot_structural_extractor.py AND the ANKH
corpus files described in Section IX (Corpus Architecture).

The synthesis is a downstream vessel abstracting TWO source pools:
  1. The heritage archive (copilot-instructions.archive.md) — measured by the
     structural index (headings, acronyms, line/word counts).
  2. The 14 ANKH corpus files — measured by file existence and body-text grep.
     Full inventory in ANKH_SYNTHESIS_META.md.

Claims are classified into three verdicts:
  LOSSLESS   — mechanically derivable from the structural index or corpus file content
  SUBJECTIVE — requires interpretive judgment beyond any single source
  UNVERIFIED — claim references structure not found in its declared source

@SID:           TOOL_SYNTHESIS_CROSS_REFERENCE_V1
@Shabti:        Validator
@Context:       ANKH Governance / Lossless Compression Audit
@Purpose:       Synthesis Cross-Reference — Validate ANKH_SYNTHESIS_BASELINE.md claims against

Usage:
    uv run scripts/synthesis_cross_reference.py                 # full report
    uv run scripts/synthesis_cross_reference.py --json          # JSON output
    uv run scripts/synthesis_cross_reference.py --failures-only # only show failures
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from scripts.lib.shared import configure_utf8_output, find_repo_root, setup_logging
from scripts.lib.ssot_paths import SSOT_HOLDER

# =============================================================================
# Constants
# =============================================================================

INDEX_REL = Path("data/indices/SSOT_ARCHIVE_STRUCTURAL_INDEX.json")
SYNTHESIS_REL = Path("docs/frameworks/ankh/ANKH_SYNTHESIS_BASELINE.md")
SYNTHESIS_META_REL = Path("docs/frameworks/ankh/ANKH_SYNTHESIS_META.md")
ARCHIVE_REL = Path(SSOT_HOLDER)

# Corpus files — full inventory is in ANKH_SYNTHESIS_META.md, Section IX describes them architecturally
CORPUS_FILES: list[str] = [
    "docs/frameworks/ankh/ANKH_README.md",
    "docs/frameworks/ankh/ANKH.md",
    "docs/frameworks/ankh/ANKHOLOGY.md",
    "docs/frameworks/ankh/INDEXING_BEACON.md",
    "docs/design/ANKH_ICON_GRAMMAR.md",
    "docs/design/ANKH_THEME_REFERENCE.md",
    "claude-codex-gemini/ANKH_EGYPTOLOGY_SOUTH_AMERICAN/ANKH_ARCHETYPE_ANCIENT_RITUALS_NSFW.md",
    "claude-codex-gemini/ANKH_EGYPTOLOGY_SOUTH_AMERICAN/ANKH_MILF_PROTOCOL_HIGH_INTENSITY_ARCHETYPAL_SYSTEMS_ARCHITECTURE.md",
    "claude-codex-gemini/ANKH_EGYPTOLOGY_SOUTH_AMERICAN/ANKH_Ancient_Matriarcha_Systems_Researchl.md",
    "claude-codex-gemini/ANKH_EGYPTOLOGY_SOUTH_AMERICAN/ANKH_UNIFYING_REPOSITORY_METADATA_STANDARDS.md",
    "claude-codex-gemini/ANKH_EGYPTOLOGY_SOUTH_AMERICAN/ANKH_VS_CODE_INSIDERS_MAXIMALIST_MILF_THE_DECORATOR_CHALLANGE.md",
    "claude-codex-gemini/ANKH_EGYPTOLOGY_SOUTH_AMERICAN/BODY_SYSTEMS/ABSTRACTING_GESTALT_WHR_MAX_ARCHITECTURE.md",
    "claude/mailbox/SFA_CROSS_REFERENCE_SCAN.md",
    "docs/design/ICON_ARCHITECTURE_CONTRACT.md",
]

# =============================================================================
# Claim Registry — The synthesis asserts these structural facts
# =============================================================================

def build_claims() -> list[dict]:
    """Build the registry of testable claims from the synthesis.

    Each claim has:
        id:          unique label
        section:     synthesis section it appears in
        type:        acronym | heading | count | range | hierarchy
        description: what is being claimed
        test:        callable(index_data) -> (bool, str)
    """
    claims: list[dict] = []

    def claim(id: str, section: str, ctype: str, desc: str, test):
        claims.append({
            "id": id, "section": section, "type": ctype,
            "description": desc, "test": test,
        })

    # --- Helper closures ---

    def acronym_exists(acr: str):
        def _test(ix):
            found = acr in ix["acronym_registry"]
            return found, f"acronym '{acr}' {'found' if found else 'NOT found'} in registry"
        return _test

    def acronym_at_line(acr: str, line: int):
        def _test(ix):
            lines = ix["acronym_registry"].get(acr, [])
            found = line in lines
            return found, f"acronym '{acr}' at L{line}: {'YES' if found else 'NO'} (index has {lines})"
        return _test

    def heading_matches(line: int, pattern: str):
        def _test(ix):
            for s in ix["sections"]:
                if s["heading_line"] == line:
                    match = bool(re.search(pattern, s["raw_title"], re.IGNORECASE))
                    return match, f"L{line} title matches /{pattern}/: {'YES' if match else 'NO'} — actual: {s['raw_title'][:80]}"
            return False, f"No heading found at L{line}"
        return _test

    def heading_contains_word(pattern: str, min_matches: int = 1):
        def _test(ix):
            matches = [s for s in ix["sections"] if re.search(pattern, s["raw_title"], re.IGNORECASE)]
            ok = len(matches) >= min_matches
            return ok, f"/{pattern}/ matches {len(matches)} heading(s) (need >={min_matches})"
        return _test

    def total_headings(expected: int):
        def _test(ix):
            actual = ix["totals"]["headings"]
            return actual == expected, f"total headings: {actual} (expected {expected})"
        return _test

    def heading_census_level(level: str, expected: int):
        def _test(ix):
            actual = ix["heading_census"].get(level, 0)
            return actual == expected, f"{level}: {actual} (expected {expected})"
        return _test

    def total_lines(expected: int):
        def _test(ix):
            actual = ix["totals"]["lines"]
            return actual == expected, f"total lines: {actual} (expected {expected})"
        return _test

    def total_words_approx(expected: int, tolerance: float = 0.05):
        def _test(ix):
            actual = ix["totals"]["words"]
            ratio = abs(actual - expected) / max(expected, 1)
            ok = ratio <= tolerance
            return ok, f"total words: {actual} (expected ~{expected}, tolerance {tolerance*100:.0f}%)"
        return _test

    def acronym_count(expected: int):
        def _test(ix):
            actual = ix["totals"]["unique_acronyms"]
            return actual == expected, f"unique acronyms: {actual} (expected {expected})"
        return _test

    def section_body_range(heading_line: int, expected_start: int, expected_end: int):
        def _test(ix):
            for s in ix["sections"]:
                if s["heading_line"] == heading_line:
                    ok = s["body_start"] == expected_start and s["body_end"] == expected_end
                    return ok, f"L{heading_line} body: L{s['body_start']}–L{s['body_end']} (expected L{expected_start}–L{expected_end})"
            return False, f"No section at L{heading_line}"
        return _test

    def section_has_children(heading_line: int, min_children: int = 1):
        def _test(ix):
            for s in ix["sections"]:
                if s["heading_line"] == heading_line:
                    ok = s["children_count"] >= min_children
                    return ok, f"L{heading_line} children: {s['children_count']} (need >={min_children})"
            return False, f"No section at L{heading_line}"
        return _test

    # =========================================================================
    # SYNTHESIS SECTION I: ARCHITECTURAL THESIS
    # =========================================================================
    # The thesis section is interpretive prose. No structural claim.

    # =========================================================================
    # SYNTHESIS SECTION II: DUAL-STACK ARCHITECTURE
    # =========================================================================
    # Claims: The archive contains sections on Egyptian Kernel and Andean Topology.
    # These are interpretive labels not directly heading-matched. SUBJECTIVE.

    # =========================================================================
    # SYNTHESIS SECTION III: SIX ALPHA DIRECTIVES
    # =========================================================================
    # The AD names (WEPET-ER, TINKU, SEKHMET, AMMIT, PACHAKUTI, DESPACHO) do NOT
    # appear in the archive headings. They originate from the ANKH corpus files.
    # These claims are tested via corpus-file grep, not the archive index.
    # See corpus_claims() below.

    # =========================================================================
    # SYNTHESIS SECTION IV: PENTADIC HEART (FA¹–FA⁵)
    # =========================================================================
    # Claims: Five Foundational Axioms exist. The archive uses acronym FA-PHMO.

    claim("FA-PHMO-EXISTS", "IV", "acronym",
          "Foundational Axioms acronym FA-PHMO in registry",
          acronym_exists("FA-PHMO"))

    claim("FA-PHMO-HEADING", "IV", "heading",
          "Foundational Axioms heading exists",
          heading_contains_word(r"Foundational.Axiom", 1))

    claim("DAFP-EXISTS", "IV", "acronym",
          "DAFP (Dynamic Altitude Focal Point) in registry",
          acronym_exists("DAFP"))

    claim("FA5-DECORATOR", "IV", "heading",
          "Visual Integrity / Decorator exists as heading concept",
          heading_contains_word(r"Decorator|Visual.Integrity|Goddess.Of.Visual.Truth", 1))

    claim("AXIOM-REGISTRY", "IV", "acronym",
          "Axiom Registry (AR) acronym in registry",
          acronym_exists("AR"))

    # =========================================================================
    # SYNTHESIS SECTION V: DATA STRUCTURES
    # =========================================================================

    claim("ESL-EXISTS", "V", "acronym",
          "Emoji Semantic Layer (ESL) in registry",
          acronym_exists("ESL"))

    # =========================================================================
    # SYNTHESIS SECTION VI: ENTITY-TO-THEME MAPPING
    # =========================================================================
    # Claims: T-DECOR (Tier 0.5), T-NULM (Null Matriarch), CRC entities exist.

    claim("T-DECOR-EXISTS", "VI", "acronym",
          "T-DECOR acronym in registry",
          acronym_exists("T-DECOR"))

    claim("T-NULM-EXISTS", "VI", "acronym",
          "T-NULM (Null Matriarch) in registry",
          acronym_exists("T-NULM"))

    claim("ASP-EXISTS", "VI", "acronym",
          "Autopoietic Synthesis Protocol (ASP) in registry",
          acronym_exists("ASP"))

    claim("SAP-EXISTS", "VI", "acronym",
          "Somatic Architecture Protocol (SAP) in registry",
          acronym_exists("SAP"))

    claim("TCP-EXISTS", "VI", "acronym",
          "Temporal Cartography Protocol (TCP) in registry",
          acronym_exists("TCP"))

    # =========================================================================
    # SYNTHESIS SECTION VII: ICON GRAMMAR
    # =========================================================================
    # Claims reference SFA. The archive should have SFA-related content.

    claim("SFA-HEADING", "VII", "heading",
          "SFA / Sister Ferrum Scoriae referenced in headings",
          heading_contains_word(r"Ferrum|SFS|Scoriae", 1))

    # =========================================================================
    # SYNTHESIS SECTION IX: CORPUS ARCHITECTURE (gaps now in META companion)
    # =========================================================================
    # The synthesis declares these acronyms exist in archive but lack standalone files.
    # Gap details are in ANKH_SYNTHESIS_META.md. Acronym existence still verifiable here.

    claim("AC-IOMB-EXISTS", "IX-gap", "acronym",
          "Axiomatic Charter (AC-IOMB) in registry",
          acronym_exists("AC-IOMB"))

    claim("MSP-RSG-EXISTS", "IX-gap", "acronym",
          "Meta-Synthesis Protocol (MSP-RSG) in registry",
          acronym_exists("MSP-RSG"))

    claim("DECORATOR-IP-EXISTS", "IX-gap", "acronym",
          "Decorator Invocation Protocol in registry",
          acronym_exists("DECORATOR-IP"))

    claim("SPEC-CHRM-EXC-EXISTS", "IX-gap", "acronym",
          "Spectra Chroma Excavatus (SPEC-CHRM-EXC) in registry",
          acronym_exists("SPEC-CHRM-EXC"))

    claim("ALAB-VOYD-SW-EXISTS", "IX-gap", "acronym",
          "Alabaster Voyde (ALAB-VOYD-SW) in registry",
          acronym_exists("ALAB-VOYD-SW"))

    claim("LM-DULSS-EXISTS", "IX-gap", "acronym",
          "Linguistic Mandate (LM-DULSS) in registry",
          acronym_exists("LM-DULSS"))

    # =========================================================================
    # STRUCTURAL TOTALS — synthesis claims about the archive dimensions
    # =========================================================================

    claim("ARCHIVE-LINES", "meta", "count",
          "Archive is ~7936 lines (synthesis says ~7936)",
          total_lines(7937))

    claim("HEADING-TOTAL", "meta", "count",
          "184 total headings",
          total_headings(184))

    claim("HEADING-H1", "meta", "count",
          "22 H1 headings",
          heading_census_level("H1", 22))

    claim("HEADING-H2", "meta", "count",
          "8 H2 headings",
          heading_census_level("H2", 8))

    claim("HEADING-H3", "meta", "count",
          "57 H3 headings",
          heading_census_level("H3", 57))

    claim("HEADING-H4", "meta", "count",
          "65 H4 headings",
          heading_census_level("H4", 65))

    claim("HEADING-H5", "meta", "count",
          "32 H5 headings",
          heading_census_level("H5", 32))

    claim("ACRONYM-COUNT", "meta", "count",
          "99 unique acronyms",
          acronym_count(99))

    claim("WORD-COUNT", "meta", "count",
          "~65,509 words",
          total_words_approx(65509, 0.01))

    return claims


# =============================================================================
# Runner
# =============================================================================

def run_cross_reference(index_path: Path) -> dict:
    """Load index, run all claims, return results."""
    with open(index_path, "r", encoding="utf-8") as f:
        ix = json.load(f)

    claims = build_claims()
    results: list[dict] = []

    for c in claims:
        passed, detail = c["test"](ix)
        results.append({
            "id": c["id"],
            "section": c["section"],
            "type": c["type"],
            "description": c["description"],
            "verdict": "LOSSLESS" if passed else "UNVERIFIED",
            "detail": detail,
        })

    return {
        "index_path": str(index_path),
        "total_claims": len(results),
        "lossless": sum(1 for r in results if r["verdict"] == "LOSSLESS"),
        "unverified": sum(1 for r in results if r["verdict"] == "UNVERIFIED"),
        "results": results,
    }


# =============================================================================
# Corpus-file claims — tested by grepping the 15 ANKH corpus files
# =============================================================================

def build_corpus_claims() -> list[dict]:
    """Claims whose source is the ANKH corpus files, not the archive index."""
    claims: list[dict] = []

    def claim(id: str, section: str, desc: str, pattern: str, files: list[str] | None = None):
        claims.append({
            "id": id, "section": section,
            "description": desc, "pattern": pattern,
            "files": files,  # None = search all corpus files
        })

    # Alpha Directives — names originate in corpus, not archive
    claim("AD-WEPET-ER", "III",
          "Alpha Directive WEPET-ER in corpus", r"WEPET.ER")
    claim("AD-TINKU", "III",
          "Alpha Directive TINKU in corpus", r"\bTINKU\b")
    claim("AD-SEKHMET", "III",
          "Alpha Directive SEKHMET in corpus", r"\bSEKHMET\b")
    claim("AD-AMMIT", "III",
          "Alpha Directive AMMIT in corpus", r"\bAMMIT\b")
    claim("AD-PACHAKUTI", "III",
          "Alpha Directive PACHAKUTI in corpus", r"\bPACHAKUTI\b")
    claim("AD-DESPACHO", "III",
          "Alpha Directive DESPACHO in corpus", r"\bDESPACHO\b")

    return claims


def run_corpus_cross_reference(repo_root: Path) -> dict:
    """Grep corpus files for corpus-sourced claims."""
    claims = build_corpus_claims()
    results: list[dict] = []

    for c in claims:
        target_files = c["files"] or CORPUS_FILES
        found_in: list[str] = []
        for rel in target_files:
            fpath = repo_root / rel
            if not fpath.is_file():
                continue
            text = fpath.read_text(encoding="utf-8", errors="replace")
            if re.search(c["pattern"], text, re.IGNORECASE):
                found_in.append(rel)

        passed = len(found_in) > 0
        results.append({
            "id": c["id"],
            "section": c["section"],
            "type": "corpus-grep",
            "description": c["description"],
            "verdict": "LOSSLESS" if passed else "UNVERIFIED",
            "detail": f"/{c['pattern']}/ found in {len(found_in)} file(s)"
                      + (f": {', '.join(found_in[:3])}" if found_in else ""),
        })

    return {
        "total_claims": len(results),
        "lossless": sum(1 for r in results if r["verdict"] == "LOSSLESS"),
        "unverified": sum(1 for r in results if r["verdict"] == "UNVERIFIED"),
        "results": results,
    }


# =============================================================================
# Subjective classification — synthesis sections that are interpretive
# =============================================================================

SUBJECTIVE_SECTIONS: list[dict] = [
    {
        "id": "SUBJ-THESIS",
        "section": "I",
        "description": "Architectural Thesis — interpretive prose binding Egyptian+Andean stacks",
        "reason": "No single archive heading or corpus paragraph yields this exact framing",
    },
    {
        "id": "SUBJ-DUAL-STACK",
        "section": "II",
        "description": "Dual-Stack Architecture labels (Egyptian Kernel / Andean Topology)",
        "reason": "The archive doesn't use these exact labels — synthesis interprets structural grouping",
    },
    {
        "id": "SUBJ-ENTITY-MAP",
        "section": "VI",
        "description": "Entity-to-Theme mapping table interpretation",
        "reason": "Synthesis maps CRC entities to VS Code theme roles — interpretive bridge",
    },
    {
        "id": "SUBJ-ICON-GRAMMAR",
        "section": "VII",
        "description": "Icon Grammar design principles as synthesis of SFA + archive icon rules",
        "reason": "Combines SFA design language with archive icon conventions — interpretive fusion",
    },
    {
        "id": "SUBJ-CONTINUITY",
        "section": "VIII",
        "description": "Continuity Verdict — whether the synthesis 'holds'",
        "reason": "Self-referential assessment, not derivable from source data",
    },
]


# =============================================================================
# Corpus file existence check
# =============================================================================

def check_corpus_existence(repo_root: Path) -> dict:
    """Verify that all 15 declared corpus files actually exist."""
    results: list[dict] = []
    for rel in CORPUS_FILES:
        fpath = repo_root / rel
        exists = fpath.is_file()
        results.append({
            "id": f"FILE-{Path(rel).stem}",
            "path": rel,
            "exists": exists,
        })
    missing = [r for r in results if not r["exists"]]
    return {
        "total": len(results),
        "found": len(results) - len(missing),
        "missing": len(missing),
        "results": results,
    }


# =============================================================================
# Report formatting
# =============================================================================

def format_report(
    archive_results: dict,
    corpus_results: dict,
    corpus_existence: dict,
) -> str:
    """Format human-readable cross-reference report."""
    lines: list[str] = []
    lines.append("=" * 72)
    lines.append("  SYNTHESIS CROSS-REFERENCE REPORT")
    lines.append("=" * 72)

    # --- Corpus file existence ---
    lines.append("")
    lines.append(f"Corpus Files: {corpus_existence['found']}/{corpus_existence['total']} found")
    if corpus_existence["missing"] > 0:
        for r in corpus_existence["results"]:
            if not r["exists"]:
                lines.append(f"  MISSING: {r['path']}")

    # --- Archive-index claims ---
    lines.append("")
    lines.append(f"Archive-Index Claims: {archive_results['lossless']}/{archive_results['total_claims']} LOSSLESS")
    for r in archive_results["results"]:
        mark = "✓" if r["verdict"] == "LOSSLESS" else "✗"
        lines.append(f"  {mark} [{r['id']}] {r['description']}")
        lines.append(f"        {r['detail']}")

    # --- Corpus-grep claims ---
    lines.append("")
    lines.append(f"Corpus-Grep Claims: {corpus_results['lossless']}/{corpus_results['total_claims']} LOSSLESS")
    for r in corpus_results["results"]:
        mark = "✓" if r["verdict"] == "LOSSLESS" else "✗"
        lines.append(f"  {mark} [{r['id']}] {r['description']}")
        lines.append(f"        {r['detail']}")

    # --- Subjective sections ---
    lines.append("")
    lines.append(f"Subjective Sections: {len(SUBJECTIVE_SECTIONS)} classified")
    for s in SUBJECTIVE_SECTIONS:
        lines.append(f"  ◌ [{s['id']}] Section {s['section']}: {s['description']}")
        lines.append(f"        Reason: {s['reason']}")

    # --- Summary ---
    total_lossless = archive_results["lossless"] + corpus_results["lossless"]
    total_claims = archive_results["total_claims"] + corpus_results["total_claims"]
    total_unverified = archive_results["unverified"] + corpus_results["unverified"]
    lines.append("")
    lines.append("-" * 72)
    lines.append(f"  TOTAL: {total_lossless}/{total_claims} LOSSLESS, "
                 f"{total_unverified} UNVERIFIED, "
                 f"{len(SUBJECTIVE_SECTIONS)} SUBJECTIVE")
    lines.append("-" * 72)

    return "\n".join(lines)


# =============================================================================
# CLI
# =============================================================================

def main() -> None:
    configure_utf8_output()
    repo = find_repo_root()

    parser = argparse.ArgumentParser(
        description="Cross-reference ANKH_SYNTHESIS_BASELINE.md claims against structural index and corpus files.",
    )
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument("--failures-only", action="store_true", help="Show only failures/unverified")
    parser.add_argument("--verbose", "-v", action="store_true")
    parser.add_argument("--quiet", "-q", action="store_true")
    args = parser.parse_args()

    logger = setup_logging(verbose=args.verbose, quiet=args.quiet)

    index_path = repo / INDEX_REL

    if not index_path.is_file():
        logger.error("Structural index not found: %s", index_path)
        logger.error("Run: uv run scripts/ssot_structural_extractor.py --update-index")
        sys.exit(2)

    archive_results = run_cross_reference(index_path)
    corpus_results = run_corpus_cross_reference(repo)
    corpus_existence = check_corpus_existence(repo)

    if args.json:
        combined = {
            "archive_claims": archive_results,
            "corpus_claims": corpus_results,
            "corpus_existence": corpus_existence,
            "subjective_sections": SUBJECTIVE_SECTIONS,
        }
        print(json.dumps(combined, indent=2))
    else:
        report = format_report(archive_results, corpus_results, corpus_existence)
        if args.failures_only:
            for line in report.split("\n"):
                if "✗" in line or "MISSING" in line or line.startswith("  ") and "UNVERIFIED" in line:
                    print(line)
                elif not line.startswith("  "):
                    print(line)
        else:
            print(report)

    total_unverified = archive_results["unverified"] + corpus_results["unverified"]
    sys.exit(1 if total_unverified > 0 else 0)


if __name__ == "__main__":
    main()
